Merge RamSoundFont, FileRenderer, gitignore and other goodies
nwhitehead/pyfluidsynth pull request #27
Opened 2020-11-07 09:08 UTC by ChristianRomberg

Hi @pedromsilvapt.
Seeing that you made some extensive and pretty nice looking additions to pyfluidsynth, I was wondering if you could merge them back into the base repository.
Greetings,
Chris

2020-11-16 23:27 UTC, pedromsilvapt commented
Hi @ChristianRomberg,
Sorry for the late reply. I'd be happy to merge them back, but to be honest I feel the code I did is a little bit of a mess right now, and some small parts are maybe too specific for the usecase I had. I was thinking of maybe creating a specific branch, where we could discuss what too include and what not, as well as allowing me to cleanup some stuff before merging.
What do you think?

2021-01-08 19:10 UTC, ChristianRomberg commented
Jeez I am so sorry. I did not mean to ghost this conversation. Of course, that sounds great.

2021-01-09 14:11 UTC, pedromsilvapt commented
Don't worry, it's ok. I haven't had much time myself to work on it, but will try to do it soon.

2024-04-27 12:59 UTC, cclauss commented on pyfluidsynth.py
> -    find_library('libfluidsynth-3') or \
Please revert this change and rebase.  It is best to install the more current library `libfluidsynth-3` before trying earlier libraries (`libfluidsynth-2` and `libfluidsynth-1`).

2024-04-27 13:03 UTC, cclauss commented on pyfluidsynth.py
> +except:
Please avoid bare `except`:
* https://peps.python.org/pep-0008/#programming-recommendations
* https://docs.astral.sh/ruff/rules/bare-except/
* https://realpython.com/the-most-diabolical-python-antipattern/

2024-04-27 13:06 UTC, cclauss commented on setup.py
> +setup (name = 'pyFluidSynth-musikla',
# ???

2024-04-27 13:06 UTC, cclauss commented on setup.py
> +       url = 'https://github.com/pedromsilvapt/pyfluidsynth',
# ???

2024-04-27 13:07 UTC, cclauss commented on pyfluidsynth.py
> +        for opt,val in iteritems(kwargs):
Why go backwards to Python 2?!?

2024-04-27 13:08 UTC, cclauss requested changes
Please rebase.

2024-04-28 04:19 UTC, cclauss commented on pyfluidsynth.py
> +        if nbframes == 2147483647:
Please add a comment about where this number comes from.
```suggestion
        if nbframes == 2_147_483_647:
```

2024-10-20 09:13 UTC, closed without merging